# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SrcFingerprint < Formula
  desc "src-fingerprint is a CLI util to easily compute the fileshas associated to a set of git repositories."
  homepage ""
  version "0.15.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/GitGuardian/src-fingerprint/releases/download/v0.15.0/src-fingerprint_0.15.0_Darwin_arm64.tar.gz", :using => CurlDownloadStrategy
      sha256 "803a581f1c751ccde4ea808f090867e4efcb99ddfb467b61683ab6a5db443ca2"

      def install
        bin.install "src-fingerprint"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/GitGuardian/src-fingerprint/releases/download/v0.15.0/src-fingerprint_0.15.0_Darwin_amd64.tar.gz", :using => CurlDownloadStrategy
      sha256 "c08484193d966246d0ddbd54c8c225b8b621fc8c2f6491e24a5d3f64889bd3c7"

      def install
        bin.install "src-fingerprint"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/GitGuardian/src-fingerprint/releases/download/v0.15.0/src-fingerprint_0.15.0_Linux_amd64.tar.gz", :using => CurlDownloadStrategy
      sha256 "830f58c3574ff4f666d601084d91913d1ebb64dd2e04d9131867a9ff52150b6d"

      def install
        bin.install "src-fingerprint"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/GitGuardian/src-fingerprint/releases/download/v0.15.0/src-fingerprint_0.15.0_Linux_arm64.tar.gz", :using => CurlDownloadStrategy
      sha256 "4a42638a46c0d1e6f724de7f311d07e1ac194ad224651970078e7b7289ac84a8"

      def install
        bin.install "src-fingerprint"
      end
    end
  end
end
